---
title: "Ensaios Não Destrutivos para Avaliação de Estruturas e Fundações em Concreto"
author: "Prof. Remo Magalhães de Souza, Eng. Civil, M.Sc , Ph.D."
format:
  revealjs:
    theme: dracula 
    transition: slide
    slide-level: 2
    width: 2000
    height: 1125
    margin: 0.02
    css: slides/includes/slides-layout.scss
    filters:
      - slides/filters/normalize_carousel_attrs.lua
      - slides/filters/slide_templates.py



---

## Principais Ensaios Não Destrutivos (END) para avaliação de estruturas de concreto

::: {.incremental}
1. **Ensaio com esclerômetro** -- para estimativa da resistência do concreto à compressão *in-situ*, por meio da avaliação da dureza superficial do concreto
2. **Ensaios com ultrassom** -- para verificação da integridade do concreto e avaliação da resistência a compressão e módulo de elasticidade
3. **Ensaio com pacômetro** -- para detecção e determinação do diâmetro de armaduras e espessura de cobrimento
4. **Ensaios de potencial de corrosão** -- para identificação de áreas com maior probabilidade de ocorrência de corrosão nas armaduras dos elementos estruturais em concreto armado
5. **Ensaios de frente de carbonatação** -- para verificação da carbonatação do concreto
6. **Ensaios de extensometria (ET)** -- este ensaio consiste na instalação de  extensômetros elétricos de resistência (*strain-gages*) em uma estrutura, visando a medição em tempo real de deformações e tensões reais decorrentes de um determinado carregamento. Quando são instalados vários sensores em uma mesma seção de um elemento estrutural, também é possível se determinar os esforços internos nesta seção
:::


<!-- Esclerometria - Slide 00 - divider -->
# 1. Ensaio de esclerometria para estimativa da resistência do concreto {.title-slide}


---

<!-- Esclerometria - Slide 01 -->

::: {.tpl-text-carousel title="1. Ensaio de esclerometria para estimativa da resistência do concreto" subtitle="1.1. Equipamento, procedimento normativo e execução do ensaio"
        img="ppt/media/image4.jpeg" 
          alt="Esclerômetro digital marca Proceq" 
        img_norma="ppt/media/esclerometria/ABNT-NBR-7584-2012.png" 
          alt_norma="Norma ABNT NBR-7584-2012 - Concreto endurecido -- Avaliação da dureza superficial pelo esclerômetro de reflexão -- Método de Ensaio"     
        img_mecanismo="ppt/media/esclerometria/esclerometroPortuguesRecorte.png" 
          alt_mecanismo="Mecanismo de funcionamento do esclerômetro"   
        img_bigorna="ppt/media/esclerometria/NBR-7584_2012_Figura01-bigorna.png" 
          alt_bigorna="Bigorna de aço para calibração do esclerômetro. Ref.: Figura 1, NBR 7584:2012"        
        img_area="ppt/media/esclerometria/NBR-7584-2012-Figura02-Area-de-ensaio.png" 
          alt_area="Área de ensaio e pontos de impacto. Ref.: Figura 2, NBR 7584:2012"   
        img_locais="ppt/media/esclerometria/NBR-7584_2012_Figura03-locais-recomendaveis.png" 
          alt_locais="Locais recomendáveis para aplicação do esclerômetro. Ref.: Figura 3, NBR 7584:2012"      
        img_ponte="ppt/media/esclerometria/190909-MRS-PonteParaibaII-Esclerometria01.jpeg" 
          alt_ponte="Execução do ensaio, pela empresa Dynamis Techne, em uma ponte ferroviária em concreto armado, localizada em Cruzeiro-SP." 
        carousel="true" }

- **Esclerômetro** -- Esclerômetro digital marca Proceq

::: {.incremental}
- **Norma de referência** -- ABNT NBR 7584:2012 - Concreto endurecido -- Avaliação da dureza superficial pelo esclerômetro de reflexão -- Método de Ensaio
- **Mecanismo de funcionamento** -- O esclerômetro consiste em uma massa-martelo que, impulsionada por uma mola, se choca com a área de ensaio através de uma haste e, a partir da energia de impacto e do deslocamento de retorno da haste, é possível se obter um valor de *dureza superficial* do concreto
- **Calibração do equipamento** -- O esclerômetro deve ser aferido antes de sua utilização ou a cada 300 impactos realizados na mesma inspeção, por meio de ensaios em bigornas de aço
- **Área de ensaio** -- Em cada área de ensaio, devem ser efetuados 16 impactos, formando um grid 4x4, com espaçamento de 30mm
- **Locais recomendáveis para ensaio** -- Sempre que possível, o ensaio deve ser realizado na posição de maior momento de inércia do elemento estrutural
- **Exemplo de ensaio** -- Execução do ensaio em uma *ponte ferroviária* em concreto armado, localizada em Cruzeiro-SP

:::

:::


<!-- Esclerometria - Slide 02 -->
## 1.2. Análise dos resultados e correlação com resistência à compressão

::: {.incremental}
- **Média inicial** - Calcular a média aritmética dos 16 valores individuais (impactos) dos índices esclerométricos
  correspondentes a uma única área de ensaio;
- **Resultados espúrios** - *Desprezar* todo índice esclerométrico individual que esteja afastado em *mais de 10%* do valor médio obtido e calcular a nova média aritmética;
- **Índice esclerométrico médio final** 
  - O índice ﬁnal deve ser obtido com no mínimo *cinco* valores individuais;
  - Quando isso não for possível, o ensaio esclerométrico dessa área deve ser desconsiderado;
  - *Nenhum* dos índices esclerométricos individuais restantes deve diferir em *mais de 10%* da média ﬁnal;
  - Se isso ocorrer, o ensaio esclerométrico dessa área deve ser desconsiderado.
:::
