---
title: "Ensaios Não Destrutivos para Avaliação de Estruturas e Fundações em Concreto"
author: "Prof. Remo Magalhães de Souza, Eng. Civil, M.Sc , Ph.D."

carbonatacao:
  item: "1."
  topic: "Ensaio de carbonatação do concreto"
  subtopic1: "1. Materiais, procedimento normativo e execução do ensaio"
  subtopic2: "2. Tratamento dos resultados"


format:
  revealjs:
    theme: dracula 
    transition: slide
    slide-level: 2
    width: 2000
    height: 1125
    margin: 0.02
    css: slides/includes/slides-layout.scss
    filters:
      - slides/filters/normalize_carousel_attrs.lua
      - slides/filters/slide_templates.py


---

<!-- Carbonatação - Slide 1.0 - divider -->
# {{< meta carbonatacao.item >}} {{< meta carbonatacao.topic >}} {.title-slide}


---

<!-- Carbonatacao - Slide 1.1 -->

::: {.tpl-text-carousel title="{{< meta carbonatacao.item >}} {{< meta carbonatacao.topic >}}" subtitle="{{< meta carbonatacao.item >}}{{< meta carbonatacao.subtopic1 >}}"
        img="media/esclerometria/esclerometro-MetroTokyo.png" 
          alt="Esclerômetro anlógico marca MetroTokyo"   
        img_esclerometro="media/esclerometria/esclerometro-Proceq.jpeg" 
          alt_esclerometro="Esclerômetro digital marca Proceq"   
        img_norma="media/esclerometria/ABNT-NBR-7584-2012.png" 
          alt_norma="Norma ABNT NBR-7584-2012 - Concreto endurecido -- Avaliação da dureza superficial pelo esclerômetro de reflexão -- Método de Ensaio"     
        img_mecanismo="media/esclerometria/esclerometroPortuguesRecorte.png" 
          alt_mecanismo="Mecanismo de funcionamento do esclerômetro"   
        img_bigorna="media/esclerometria/NBR-7584_2012_Figura01-bigorna.png" 
          alt_bigorna="Bigorna de aço para calibração do esclerômetro. Ref.: Figura 1, NBR 7584:2012" 
        img_calibracao="media/esclerometria/Calibracao-esclerometro-com-bigorna-01.jpeg" 
          alt_calibracao="Calibração do esclerômetro com bigorna de aço, pela empresa Dynamis Techne"  
        img_calibracao02="media/esclerometria/Calibracao-esclerometro-com-bigorna-02.jpeg" 
          alt_calibracao02="Calibração do esclerômetro com bigorna de aço, pela empresa Dynamis Techne"                   
        img_area="media/esclerometria/NBR-7584-2012-Figura02-Area-de-ensaio.png" 
          alt_area="Área de ensaio e pontos de impacto. Ref.: Figura 2, NBR 7584:2012"   
        img_locais="media/esclerometria/NBR-7584_2012_Figura03-locais-recomendaveis.png" 
          alt_locais="Locais recomendáveis para aplicação do esclerômetro. Ref.: Figura 3, NBR 7584:2012"      
        img_ponte="media/esclerometria/190909-MRS-PonteParaibaII-Carbonatacao01.jpeg" 
          alt_ponte="Execução do ensaio, pela empresa Dynamis Techne, em uma ponte ferroviária em concreto armado, localizada em Cruzeiro-SP." 
        img_estaca="media/esclerometria/250903-HydroOS14-Silo-Carbonatacao01.jpg" 
          alt_estaca="Execução do ensaio, pela empresa Dynamis Techne, em uma estaca de concreto, em um silo em área portuária" 
        carousel="true" }

- **Esclerômetro** -- Equipamento utilizado para a realização do ensaio de Carbonatacao, disponível em versões analógica e digital

::: {.incremental}
- **Norma de referência** -- ABNT NBR 7584:2012 - Concreto endurecido -- Avaliação da dureza superficial pelo esclerômetro de reflexão -- Método de Ensaio
- **Mecanismo de funcionamento** -- O esclerômetro consiste em uma massa-martelo que, impulsionada por uma mola, se choca com a área de ensaio através de uma haste e, a partir da energia de impacto e do deslocamento de retorno da haste, é possível se obter um valor de *dureza superficial* do concreto
- **Calibração do equipamento** -- O esclerômetro deve ser aferido antes de sua utilização ou a cada 300 impactos realizados na mesma inspeção, por meio de ensaios em bigornas de aço
- **Área de ensaio** -- Em cada área de ensaio, devem ser efetuados 16 impactos, formando um grid 4x4, com espaçamento de 30mm
- **Locais recomendáveis para ensaio** -- Sempre que possível, o ensaio deve ser realizado na posição de maior momento de inércia do elemento estrutural
- **Exemplos de ensaio** -- Execução do ensaio de Carbonatacao realizados pela empresa Dynamis Techne

:::

:::


---

<!-- Carbonatacao - Slide 1.2 -->
::: {.tpl-text title="{{< meta carbonatacao.item >}} {{< meta carbonatacao.topic >}}" subtitle="{{< meta carbonatacao.item >}}{{< meta carbonatacao.subtopic2 >}}"}
::: {.incremental}

- **Média inicial** - Calcular a média aritmética dos 16 valores individuais (impactos) dos índices esclerométricos
  correspondentes a uma única área de ensaio;
- **Resultados espúrios** - *Desprezar* todo índice esclerométrico individual que esteja afastado em *mais de 10%* do valor médio obtido e calcular a nova média aritmética;
- **Índice esclerométrico médio final** 
  - O índice ﬁnal deve ser obtido com no mínimo *cinco* valores individuais;
  - Quando isso não for possível, o ensaio esclerométrico dessa área deve ser desconsiderado;
  - *Nenhum* dos índices esclerométricos individuais restantes deve diferir em *mais de 10%* da média ﬁnal;
  - Se isso ocorrer, o ensaio esclerométrico dessa área deve ser desconsiderado.
:::

:::

---

<!-- Carbonatacao - Slide 1.3 -->
::: {.tpl-wide-image title="{{< meta carbonatacao.item >}}{{< meta carbonatacao.topic >}}" subtitle="{{< meta carbonatacao.item >}}{{< meta carbonatacao.subtopic2 >}}"
  img="media/esclerometria/CarbonatacaoTabela.png" 
    caption="Tabela com análise dos resultados do ensaio de Carbonatacao, incluindo os índices individuais, médias e valores espúrios." }
:::


---

<!-- Carbonatacao - Slide 1.3 -->
::: {.tpl-wide-image title="{{< meta carbonatacao.item >}}{{< meta carbonatacao.subtopic2 >}}" 
  img="media/esclerometria/CarbonatacaoTabela.png" 
    caption="Tabela com análise dos resultados do ensaio de Carbonatacao, incluindo os índices individuais, médias e valores espúrios." 
  img_conferencia="media/image5.png" 
    caption_conferencia="Etapa 2: aquisicao e conferencia de leituras" carousel="true"}
:::