<!DOCTYPE html>
<html lang="en"><head>
<script src="part02_files/libs/clipboard/clipboard.min.js"></script>
<script src="part02_files/libs/quarto-html/tabby.min.js"></script>
<script src="part02_files/libs/quarto-html/popper.min.js"></script>
<script src="part02_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="part02_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="part02_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="part02_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Prof.&nbsp;Remo Magalhães de Souza, Eng. Civil, M.Sc , Ph.D.">
  <title>Ensaios Não Destrutivos para Avaliação de Estruturas e Fundações em Concreto</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="part02_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="part02_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="part02_files/libs/revealjs/dist/theme/quarto-2740581606dc327e82f18f789b69d8a0.css">
  <link href="part02_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="part02_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="part02_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="part02_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Ensaios Não Destrutivos para Avaliação de Estruturas e Fundações em Concreto</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Remo Magalhães de Souza, Eng. Civil, M.Sc , Ph.D. 
</div>
</div>
</div>

</section>
<section id="ensaios-não-destrutivos-para-avaliação-de-estruturas-e-fundações-em-concreto" class="slide level2">
<h2>Ensaios Não Destrutivos para Avaliação de Estruturas e Fundações em Concreto</h2>
<p>Prof.&nbsp;Remo Magalhães de Souza, Eng. Civil, M.Sc , Ph.D.</p>
<p>12 de Maio de 2026</p>
</section>
<section id="principais-ensaios-não-destrutivos-end-para-avaliação-de-estruturas-de-concreto" class="slide level2">
<h2>Principais Ensaios Não destrutivos (END) para avaliação de estruturas de concreto:</h2>
<ul>
<li><strong>Ensaio com esclerômetro</strong> –&nbsp;para estimativa da resistência do concreto à compressão <em>in-situ</em>, por meio da avaliação da dureza superficial do concreto</li>
<li><strong>Ensaios com ultrassom</strong> – para verificação da integridade do concreto e avaliação da resistência a compressão e módulo de elasticidade</li>
<li><strong>Ensaio com pacômetro</strong> –&nbsp;para detecção e determinação do diâmetro de armaduras e espessura de cobrimento</li>
<li><strong>Ensaios de potencial de corrosão</strong> –&nbsp;para identificação de áreas com maior probabilidade de ocorrência de corrosão nas armaduras dos elementos estruturais em concreto armado</li>
<li><strong>Ensaios de frente de carbonatação</strong>&nbsp;– para verificação da carbonatação do concreto</li>
<li><strong>Ensaios de extensometria (ET)</strong> –&nbsp;este ensaio consiste na instalação de&nbsp; extensômetros elétricos de resistência (<em>strain-gages</em>) &nbsp;em uma estrutura, visando a medição em tempo real de deformações e tensões reais decorrentes de um determinado carregamento. Quando são instalados vários sensores em uma mesma seção de um elemento estrutural, também é possível se determinar os esforços internos nesta seção</li>
</ul>
</section>
<section id="ensaios-semi-destrutivos-para-avaliação-do-material" class="slide level2">
<h2>Ensaios semi-destrutivos para avaliação do material</h2>
<ul>
<li>Extração de testemunhos</li>
<li>Ensaios de resistência à compressão ;</li>
<li>Ensaio de módulo de elasticidade ;</li>
</ul>
<p>Ensaios não-destrutivos para avaliação de estacas</p>
<ul>
<li>PIT – Pile Integrity Test – Teste de integridade em estacas</li>
<li>Outros...</li>
</ul>
</section>
<section id="slide-4" class="slide level2">
<h2>Slide 4</h2>
<p>Últimas referências normativas nacionais</p>
<p>NBR&nbsp; 5739:2018 –&nbsp; Concreto – Ensaios de compressão de corpos-de-prova cilíndricos</p>
<p>NBR&nbsp; 7584:2012 –&nbsp; Concreto endurecido – Avaliação da dureza superficial pelo esclerômetro de reflexão</p>
<p>NBR&nbsp; 7680-1:2015 –&nbsp; Concreto – Extração, preparo, ensaio e análise de testemunhos de estruturas de concreto. Parte 1: Resistência a compressão axial</p>
<p>NBR&nbsp; 7680-2:2015 –&nbsp; Concreto – Extração, preparo, ensaio e análise de testemunhos de estruturas de concreto. Parte 2: Resistência à tração na flexão</p>
<p>NBR&nbsp; 8522-1:2021&nbsp;–&nbsp; Concreto endurecido – Determinação dos módulos de elasticidade e de deformação. Parte 1: Módulos estáticos à compressão</p>
<p>NBR&nbsp; 8522-2:2021 – &nbsp;Concreto endurecido – Determinação dos módulos de elasticidade e de deformação. Parte 2: Módulo de elasticidade dinâmico pelo método das frequências naturais de vibração</p>
<p>NBR&nbsp; 8802:2019 –&nbsp; Concreto endurecido – Determinação da velocidade de propagação de onda ultrassônica</p>
<table class="caption-top" style="width:6%;">
<colgroup>
<col style="width: 5%">
</colgroup>
<tbody>
<tr class="odd">
<td>## Slide 5</td>
</tr>
<tr class="even">
<td>Referências normativas internacionais</td>
</tr>
<tr class="odd">
<td>Norma Britânica&nbsp; BS1881-201 –&nbsp; Testing concrete. Guide to the use of non- destructive methods of test for hardened concrete</td>
</tr>
<tr class="even">
<td>Norma Alemã DIN EN 14630 –&nbsp; Products and systems for the protection and repair of concrete structures – Test methods – Determination of carbonation depth in hardened concrete by the phenolphthalein method “&nbsp;</td>
</tr>
<tr class="odd">
<td>Norma Chinesa JGJ/T 23-2001 – Technical specification for inspection of concrete compressive strength by rebound method .</td>
</tr>
<tr class="even">
<td>Norma Americana ACI 228.2R-13 - Report on Nondestructive Test Methods for Evaluation of Concrete in Structures</td>
</tr>
<tr class="odd">
<td>Norma Americana ASTM C 876 – Standard test method for corrosion potentials of uncoated steel in concrete</td>
</tr>
<tr class="even">
<td>Norma Americana ASTM – D5882 – 16 –&nbsp; Standard Test Method for Low Strain Impact Integrity Testing of Deep Foundations ” (Método de teste padrão para ensaio de integridade de estaca com baixa deformação)</td>
</tr>
<tr class="odd">
<td>## Slide 6</td>
</tr>
<tr class="even">
<td>Ensaio com esclerômetro para determinação da dureza superficial do concreto :</td>
</tr>
<tr class="odd">
<td>- Norma NBR 7584:2012 Concreto endurecido – Avaliação da dureza superficial pelo esclerômetro de reflexão – Método de Ensaio; - O esclerômetro consiste em uma massa-martelo que, impulsionada por uma mola, se choca com a área de ensaio através de uma haste;</td>
</tr>
<tr class="even">
<td>Esclerômetro Proceq – SilverSchmidt .</td>
</tr>
</tbody>
</table>
<p><img data-src="ppt/media/image4.jpeg" title="Imagem 8"></p>
<p>Esclerômetro Proceq – SilverSchmidt .</p>
<p><img data-src="ppt/media/image5.png" title="Imagem 10"></p>
</section>
<section id="slide-7" class="slide level2">
<h2>Slide 7</h2>
<p>Ensaio com esclerômetro para determinação da dureza superficial do concreto :</p>
<ul>
<li></li>
</ul>
<p><img data-src="ppt/media/image6.jpeg" title="Picture 4"></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="ppt/media/image7.jpeg" title="Picture 6"></p>
<figcaption>Résultats de recherche d'images pour «&nbsp;rebound hammer schmidt inside view&nbsp;»</figcaption>
</figure>
</div>
</section>
<section id="slide-8" class="slide level2">
<h2>Slide 8</h2>
<p>Ensaio com esclerômetro para determinação da dureza superficial do concreto</p>
<p>![Uma imagem contendo ao ar livre, neve, tábua, homem</p>
<p>Descrição gerada automaticamente](ppt/media/image8.jpg “Imagem 2”)</p>
<p>![Uma imagem contendo pessoa, jovem, homem, menino</p>
<p>Descrição gerada automaticamente](ppt/media/image9.jpeg “Imagem 6”)</p>
</section>
<section id="slide-9" class="slide level2">
<h2>Slide 9</h2>
<p>Ensaio com esclerômetro para determinação da dureza superficial do concreto</p>
<p><img data-src="ppt/media/image10.jpeg" title="Shape 211"></p>
<p><img data-src="ppt/media/image11.jpg" title="Imagem 5"></p>
</section>
<section id="slide-10" class="slide level2">
<h2>Slide 10</h2>
<p>Ensaio com esclerômetro para determinação da dureza superficial do concreto</p>

<img data-src="ppt/media/image12.png" title="Imagem 6" class="r-stretch"></section>
<section id="slide-11" class="slide level2">
<h2>Slide 11</h2>
<p>Ensaio com ultrassom determinação da velocidade de propagação da onda ultrassônica :</p>
<ul>
<li>norma NBR 8802:2019 – Concreto endurecido – Determinação da velocidade de propagação de onda ultrassônica;</li>
<li>Aplicação: verificação da integridade do concreto e avaliação da resistência a compressão e módulo de elasticidade do concreto</li>
<li></li>
</ul>

<img data-src="ppt/media/image13.jpeg" title="Picture 2" class="r-stretch quarto-figure-center"><p class="caption">Estimativa de propriedades do concreto com aparelho de ultrassom</p></section>
<section id="slide-12" class="slide level2">
<h2>Slide 12</h2>
<p>Ensaio com ultrassom determinação da velocidade de propagação da onda ultrassônica :</p>
<ul>
<li></li>
</ul>

<img data-src="ppt/media/image15.png" title="Imagem 5" class="r-stretch"></section>
<section id="slide-13" class="slide level2">
<h2>Slide 13</h2>
<p>Ensaio com ultrassom determinação da velocidade de propagação da onda ultrassônica</p>

<img data-src="ppt/media/image16.png" title="Imagem 6" class="r-stretch"><p>IS 13311: 1992 ( Non- Destructive Testing of Concrete – Methods of test – Part 1 – Ultrasonic Pulse Velocity )</p>
</section>
<section id="slide-14" class="slide level2">
<h2>Slide 14</h2>
<p>Ensaio com ultrassom determinação da velocidade de propagação da onda ultrassônica</p>

<img data-src="ppt/media/image17.gif" title="Imagem 8" class="r-stretch"><p>Relação entre velocidade de pulso ultrassônico (km/ sec ) e resistência à compressão do concreto</p>
</section>
<section id="slide-15" class="slide level2">
<h2>Slide 15</h2>
<p>Ensaio com ultrassom determinação da velocidade de propagação da onda ultrassônica</p>
<p>Relação empírica entre módulos de elasticidade estático e dinâmico e velocidade de pulso (Fonte: BS-1881:1986 – Part 203)°</p>

<img data-src="ppt/media/image18.png" title="Imagem 5" class="r-stretch"></section>
<section id="slide-16" class="slide level2">
<h2>Slide 16</h2>
<p>Ensaio com ultrassom determinação da velocidade de propagação da onda ultrassônica</p>

<img data-src="ppt/media/image19.emf" title="Imagem 3" class="r-stretch"></section>
<section id="slide-17" class="slide level2">
<h2>Slide 17</h2>
<p>Ensaio com ultrassom determinação da velocidade de propagação da onda ultrassônica</p>
<p><img data-src="ppt/media/image20.jpeg" title="Shape 200"></p>
<p><img data-src="ppt/media/image21.jpg" title="Shape 201"></p>
</section>
<section id="slide-18" class="slide level2">
<h2>Slide 18</h2>
<p>Ensaio com ultrassom determinação da velocidade de propagação da onda ultrassônica</p>

<img data-src="ppt/media/image23.png" title="Imagem 1" class="r-stretch"></section>
<section id="slide-19" class="slide level2">
<h2>Slide 19</h2>
<p>Ensaio de potencial de corrosão:</p>
<ul>
<li>norma ASTM C 876 – Standard test method for corrosion potentials of uncoated steel in concrete );</li>
<li>Ensaio necessário para identificação de áreas com maior probabilidade de ocorrência de corrosão nas armaduras dos elementos estruturais em concreto armado;</li>
<li>O ensaio consiste na utilização de um eletrodo de referência conectado por meio de um voltímetro de alta impedância ao aço da estrutura e movimentado acima da superfície do concreto;</li>
<li>Desta forma, é possível medir os potenciais na superfície do concreto para obter uma imagem característica do estado de corrosão da superfície do aço dentro do concreto</li>
<li></li>
<li></li>
</ul>
</section>
<section id="slide-20" class="slide level2">
<h2>Slide 20</h2>
<p>Ensaio de potencial de corrosão:</p>
<ul>
<li></li>
</ul>
<p><img data-src="ppt/media/image24.png" title="Imagem 3"></p>
<p>Relação entre o potencial de meia célula e o estado de corrosão na estrutura</p>
<p><img data-src="ppt/media/image25.JPG" title="Imagem 5"></p>
<p>Equipamento Canin + da marca Proceq</p>
</section>
<section id="slide-21" class="slide level2">
<h2>Slide 21</h2>
<p>Ensaio de potencial de corrosão:</p>
<ul>
<li></li>
</ul>
<p><img data-src="ppt/media/image26.jpeg" title="Imagem 7"></p>
<p><img data-src="ppt/media/image27.jpeg" title="Imagem 8"></p>
</section>
<section id="slide-22" class="slide level2">
<h2>Slide 22</h2>
<p>Ensaio de potencial de corrosão:</p>
<ul>
<li></li>
</ul>
<p><img data-src="ppt/media/image28.png" title="Imagem 9"></p>
<p><img data-src="ppt/media/image29.jpeg" title="Imagem 10"></p>
</section>
<section id="slide-23" class="slide level2">
<h2>Slide 23</h2>
<p>Ensaio com pacômetro para detecção e determinação do diâmetro de armaduras e espessura de cobrimento :</p>
<ul>
<li></li>
</ul>
<p><img data-src="ppt/media/image30.jpeg" title="Shape 213"></p>
<p><img data-src="ppt/media/image31.jpeg" title="Picture 2"></p>
</section>
<section id="slide-24" class="slide level2">
<h2>Slide 24</h2>
<p>Ensaio com pacômetro para detecção e determinação do diâmetro de armaduras e espessura de cobrimento :</p>
<ul>
<li></li>
</ul>
<p><img data-src="ppt/media/image32.jpeg" title="Imagem 4"></p>
<p>O equipamento Profometer 630, marca Proceq</p>
<p><img data-src="ppt/media/image33.jpeg" title="Imagem 6"></p>
</section>
<section id="slide-25" class="slide level2">
<h2>Slide 25</h2>
<p>Ensaio com pacômetro para detecção e determinação do diâmetro de armaduras e espessura de cobrimento :</p>
<ul>
<li></li>
</ul>
<p><img data-src="ppt/media/image34.jpeg" title="Imagem 5"></p>
<p><img data-src="ppt/media/image35.jpeg" title="Imagem 7"></p>
</section>
<section id="slide-26" class="slide level2">
<h2>Slide 26</h2>
<p>Ensaio com pacômetro para detecção e determinação do diâmetro de armaduras e espessura de cobrimento :</p>
<ul>
<li></li>
</ul>
<p><img data-src="ppt/media/image36.jpeg" title="Imagem 4"></p>
<p><img data-src="ppt/media/image37.jpeg" title="Imagem 6"></p>
</section>
<section id="slide-27" class="slide level2">
<h2>Slide 27</h2>
<p>Ensaio com pacômetro para detecção e determinação do diâmetro de armaduras e espessura de cobrimento :</p>
<ul>
<li></li>
</ul>

<img data-src="ppt/media/image38.png" title="Imagem 5" class="r-stretch"><p>a armadura longitudinal na face maior do pilar é formada por 8 barras de 3/4” dispostas na região mais próxima das arestas, e 4 barras de ½” dispostas na região central da face</p>
</section>
<section id="slide-28" class="slide level2">
<h2>Slide 28</h2>
<p>Ensaio com pacômetro para detecção e determinação do diâmetro de armaduras e espessura de cobrimento :</p>
<ul>
<li></li>
</ul>

<img data-src="ppt/media/image39.png" title="Imagem 4" class="r-stretch"></section>
<section id="slide-29" class="slide level2">
<h2>Slide 29</h2>
<p>Extração de testemunho de concreto :</p>
<ul>
<li></li>
</ul>
<p><img data-src="ppt/media/image40.jpeg" title="Shape 208"></p>
<p><img data-src="ppt/media/image41.jpeg" title="Shape 209"></p>
</section>
<section id="slide-30" class="slide level2">
<h2>Slide 30</h2>
<p>Extração de testemunho de concreto :</p>
<ul>
<li></li>
</ul>
<p><img data-src="ppt/media/image42.jpeg" title="Shape 362"></p>
<p><img data-src="ppt/media/image43.jpeg" title="Shape 363"></p>
</section>
<section id="slide-31" class="slide level2">
<h2>Slide 31</h2>
<p>Extração de testemunho de concreto :</p>
<ul>
<li></li>
</ul>

<img data-src="ppt/media/image44.jpeg" title="Imagem 7" class="r-stretch"></section>
<section id="slide-32" class="slide level2">
<h2>Slide 32</h2>
<p>Extração de testemunho de concreto :</p>
<ul>
<li></li>
</ul>
<p><img data-src="ppt/media/image45.jpeg" title="Imagem 3"></p>
<p><img data-src="ppt/media/image46.jpeg" title="Imagem 4"></p>
<p><img data-src="ppt/media/image47.jpeg" title="Imagem 5"></p>
</section>
<section id="slide-33" class="slide level2">
<h2>Slide 33</h2>
<p>Extração de testemunho de concreto :</p>
<ul>
<li></li>
</ul>
<p><img data-src="ppt/media/image48.jpeg" title="Imagem 7"></p>
<p><img data-src="ppt/media/image49.jpeg" title="Imagem 8"></p>
</section>
<section id="slide-34" class="slide level2">
<h2>Slide 34</h2>
<p>Extração de testemunho de concreto :</p>
<ul>
<li></li>
</ul>
<p><img data-src="ppt/media/image50.jpeg" title="Imagem 4"></p>
<p><img data-src="ppt/media/image51.jpeg" title="Imagem 5"></p>
</section>
<section id="slide-35" class="slide level2">
<h2>Slide 35</h2>
<p>Extração de testemunho de concreto :</p>
<ul>
<li></li>
</ul>
<p><img data-src="ppt/media/image51.jpeg" title="Imagem 5"></p>
<p><img data-src="ppt/media/image52.jpeg" title="Imagem 6"></p>
</section>
<section id="slide-36" class="slide level2">
<h2>Slide 36</h2>
<p>Ensaio de resistência a compressão e módulo de elasticidade do concreto:</p>
<p><img data-src="ppt/media/image53.jpeg" title="Imagem 4"></p>
<p><img data-src="ppt/media/image54.jpeg" title="Imagem 7"></p>
</section>
<section id="slide-37" class="slide level2">
<h2>Slide 37</h2>
<p>Ensaio de resistência a compressão e módulo de elasticidade do concreto:</p>

<img data-src="ppt/media/image55.png" title="Imagem 6" class="r-stretch"><p>[Graphic: other: http://schemas.openxmlformats.org/drawingml/2006/chart]</p>
</section>
<section id="slide-38" class="slide level2">
<h2>Slide 38</h2>
<p>Ensaio de resistência a compressão e módulo de elasticidade do concreto:</p>
<p><img data-src="ppt/media/image56.jpeg" title="Imagem 5"></p>
<p>Medidor de deformação mecânico do tipo compressômetro com bases independentes utilizados nos ensaios</p>
<p><img data-src="ppt/media/image57.jpeg" title="Imagem 6"></p>
</section>
<section id="slide-39" class="slide level2">
<h2>Slide 39</h2>
<p>Ensaio de carbonatação:</p>
<ul>
<li>O ensaio permite a identificação da existência ou não do processo de carbonatação, em função da redução do pH do concreto, o que possibilita a despassivação da armadura, e podendo levar à corrosão da mesma;</li>
<li>norma internacional DIN EN 14630 - Products and systems for the protection and repair of concrete structures – Test methods – Determination of carbonation depth in hardened concrete by the phenolphthalein method .</li>
<li>visualização da alteração do pH do concreto de cobrimento, pela aspersão de um indicador de pH, usualmente, uma solução de fenolftaleína (1 g da fenolftaleína em 50 ml de álcool etílico).</li>
<li></li>
</ul>
<p><img data-src="ppt/media/image58.png" title="Imagem 3"></p>
<p>O pH abaixo de 8 (indicação incolor) corresponde a ocorrência de carbonatação.</p>
<p><img data-src="ppt/media/image59.jpeg" title="Shape 212"></p>
</section>
<section id="slide-40" class="slide level2">
<h2>Slide 40</h2>
<p>Ensaio de carbonatação:</p>
<ul>
<li></li>
</ul>
<p><img data-src="ppt/media/image60.jpeg" title="Picture 2"></p>
<p><img data-src="ppt/media/image61.jpeg" title="Imagem 4"></p>
</section>
<section id="slide-41" class="slide level2">
<h2></h2>
<p>Instrumentação com extensômetros elétricos</p>

<img data-src="ppt/media/image62.jpeg" title="Picture 2" class="r-stretch quarto-figure-center"><p class="caption">F17_SG5_P7_SC_Conc</p></section>
<section id="slide-42" class="slide level2">
<h2>Slide 42</h2>
<p>Instrumentação com extensômetros elétricos</p>
<p>Fixação de sensores</p>
<p><img data-src="ppt/media/image63.jpeg" title="Shape 344"></p>
<p><img data-src="ppt/media/image64.jpeg" title="Shape 345"></p>
</section>
<section id="slide-43" class="slide level2">
<h2>Slide 43</h2>
<p>Sistemas de aquisição de dados</p>
<p>Prova de carga na estrutura do Píer de Navios</p>

<img data-src="ppt/media/image65.jpg" title="Imagem 2" class="r-stretch"></section>
<section id="slide-44" class="slide level2">
<h2>Slide 44</h2>
<p>PIT – Teste de Integridade em Estacas:</p>
<ul>
<li></li>
<li>Tradicionalmente, o ensaio consiste na colocação de um acelerômetro (sensor de vibração)&nbsp; no topo da estaca a ser testada, seguida da aplicação de golpes com um martelo manual.</li>
<li>O acelerômetro é fixado por meio de um material viscoso, geralmente cera de petróleo.</li>
<li>Os golpes geram uma onda de tensão, que trafega ao longo da estaca, e que sofre reflexões ao encontrar qualquer variação nas características do material (por exemplo, área de seção transversal da estaca, densidade ou módulo de elasticidade do concreto).</li>
<li>Essas reflexões causam variações na aceleração medida pelo acelerômetro. É feito então&nbsp; um registro da evolução dessa aceleração (ou da velocidade) com o tempo.</li>
<li>Como a onda de tensão trafega com uma velocidade fixa em um mesmo material, conhecendo-se a velocidade de propagação da onda e o tempo transcorrido entre a aplicação do golpe e a chegada da reflexão correspondente à variação de características, pode-se determinar a exata localização dessa variação.</li>
</ul>
<p>![Diagrama</p>
<p>Descrição gerada automaticamente](ppt/media/image66.png “Imagem 3”)</p>
</section>
<section id="slide-45" class="slide level2">
<h2>Slide 45</h2>
<p>PIT – Teste de Integridade em Estacas:</p>
<ul>
<li></li>
</ul>
<p><img data-src="ppt/media/image67.jpeg" title="Picture 2"></p>
<p>![Diagrama</p>
<p>Descrição gerada automaticamente com confiança média](ppt/media/image68.png “Imagem 1”)</p>
<p><img data-src="ppt/media/image69.jpeg" title="Picture 2"></p>
</section>
<section id="slide-46" class="slide level2">
<h2>Slide 46</h2>
<p>PIT – Teste de Integridade em Estacas:</p>
<ul>
<li></li>
</ul>


<img data-src="ppt/media/image70.png" title="Imagem 5" class="r-stretch"></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="part02_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="part02_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="part02_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="part02_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="part02_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="part02_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="part02_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="part02_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="part02_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="part02_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>